name: Symfony

on:
  push:
    branches: [ "tests", "develop" ]
  pull_request:
    branches: [ "tests" ]

permissions:
  contents: read

jobs:
  build_all_jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.0'
      - uses: actions/checkout@v3
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer update
  symfony-unit_tests:
    needs: build_all_jobs
    runs-on: ubuntu-latest
    steps:
    - name: Execute Unit tests via PHPUnit
      run: vendor/bin/phpunit tests/Unit/*

  symfony-func_tests:
    runs-on: ubuntu-latest
    needs: [build_all_jobs, symfony-unit_tests]
    steps:
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.0'
      - uses: actions/checkout@v3
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer update
      - name: Execute Unit tests via PHPUnit
        run: vendor/bin/phpunit tests/Func/*