name: Symfony

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-unit_tests:
    runs-on: ubuntu-latest
    steps:
      #  To automatically get bug fixes and new Php versions for shivammathur/setup-phps
      # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning)d
      # uses: shivammathur/setup-php@v2
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.0'
      - uses: actions/checkout@v3
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer update
      - name: Execute Unit tests via PHPUnit
        run: vendor/bin/phpunit tests/Unit/*

  symfony-func_tests:
    runs-on: ubuntu-latest
    needs: symfony-unit_tests
    steps:
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.0'
      - uses: actions/checkout@v3
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer update
      - name: Execute Func tests via WebTestCase
        run: vendor/bin/phpunit tests/Func/*
  deploy_on_another_git:
    runs-on: ubuntu-latest
    needs: symfony-func_tests
    steps:
      - name: install ssh
        run: sudo apt install ssh
      - name: deploy changes to a repo
        uses: tagus/git-deploy@v0.4.1
        with:
          changes: public
          repository: https://github.com/Freddyede/server_repo.git
          name: Freddyede
          clean_repo: true